# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoLecteur.ui',
# licensing of 'VideoLecteur.ui' applies.
#
# Created: Thu Jul 18 09:53:50 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 867)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.wLecteur = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wLecteur.sizePolicy().hasHeightForWidth())
        self.wLecteur.setSizePolicy(sizePolicy)
        self.wLecteur.setObjectName("wLecteur")
        self.verticalLayout.addWidget(self.wLecteur)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lTemps = QtWidgets.QLabel(self.centralwidget)
        self.lTemps.setObjectName("lTemps")
        self.horizontalLayout_2.addWidget(self.lTemps)
        self.sTimeLine = QtWidgets.QSlider(self.centralwidget)
        self.sTimeLine.setOrientation(QtCore.Qt.Horizontal)
        self.sTimeLine.setObjectName("sTimeLine")
        self.horizontalLayout_2.addWidget(self.sTimeLine)
        self.lTempsTotal = QtWidgets.QLabel(self.centralwidget)
        self.lTempsTotal.setObjectName("lTempsTotal")
        self.horizontalLayout_2.addWidget(self.lTempsTotal)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbPlay = QtWidgets.QPushButton(self.centralwidget)
        self.pbPlay.setObjectName("pbPlay")
        self.horizontalLayout.addWidget(self.pbPlay)
        self.pbPause = QtWidgets.QPushButton(self.centralwidget)
        self.pbPause.setObjectName("pbPause")
        self.horizontalLayout.addWidget(self.pbPause)
        self.pbStop = QtWidgets.QPushButton(self.centralwidget)
        self.pbStop.setObjectName("pbStop")
        self.horizontalLayout.addWidget(self.pbStop)
        self.pbNext = QtWidgets.QPushButton(self.centralwidget)
        self.pbNext.setObjectName("pbNext")
        self.horizontalLayout.addWidget(self.pbNext)
        self.pbPrevious = QtWidgets.QPushButton(self.centralwidget)
        self.pbPrevious.setObjectName("pbPrevious")
        self.horizontalLayout.addWidget(self.pbPrevious)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setBaseSize(QtCore.QSize(0, 100))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.wList = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wList.sizePolicy().hasHeightForWidth())
        self.wList.setSizePolicy(sizePolicy)
        self.wList.setObjectName("wList")
        self.verticalLayout_3.addWidget(self.wList)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pbAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pbAdd.setObjectName("pbAdd")
        self.horizontalLayout_4.addWidget(self.pbAdd)
        self.pbDelete = QtWidgets.QPushButton(self.centralwidget)
        self.pbDelete.setObjectName("pbDelete")
        self.horizontalLayout_4.addWidget(self.pbDelete)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.lVolume = QtWidgets.QLabel(self.centralwidget)
        self.lVolume.setObjectName("lVolume")
        self.horizontalLayout_6.addWidget(self.lVolume)
        self.dVolume = QtWidgets.QDial(self.centralwidget)
        self.dVolume.setObjectName("dVolume")
        self.horizontalLayout_6.addWidget(self.dVolume)
        self.lPourcent = QtWidgets.QLabel(self.centralwidget)
        self.lPourcent.setObjectName("lPourcent")
        self.horizontalLayout_6.addWidget(self.lPourcent)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lTemps.setText(QtWidgets.QApplication.translate("MainWindow", "0:00", None, -1))
        self.lTempsTotal.setText(QtWidgets.QApplication.translate("MainWindow", "0:00:00", None, -1))
        self.pbPlay.setText(QtWidgets.QApplication.translate("MainWindow", "Play", None, -1))
        self.pbPause.setText(QtWidgets.QApplication.translate("MainWindow", "Pause", None, -1))
        self.pbStop.setText(QtWidgets.QApplication.translate("MainWindow", "Stop", None, -1))
        self.pbNext.setText(QtWidgets.QApplication.translate("MainWindow", "Next", None, -1))
        self.pbPrevious.setText(QtWidgets.QApplication.translate("MainWindow", "Previous", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Liste de lecture: ", None, -1))
        self.pbAdd.setText(QtWidgets.QApplication.translate("MainWindow", "+", None, -1))
        self.pbDelete.setText(QtWidgets.QApplication.translate("MainWindow", "-", None, -1))
        self.lVolume.setText(QtWidgets.QApplication.translate("MainWindow", "Volume", None, -1))
        self.lPourcent.setText(QtWidgets.QApplication.translate("MainWindow", "0%", None, -1))

